### ISSUE TITLE
Integrate data provider like lazy loading functionality

### ISSUE THREAD

**Issue by stefanuebe** [stefanuebe/vaadin_fullcalendar#130]
Similar like the data provider it should be possible to set some kind of callback on the server side that is called by the client on view render time. It provides infos like range, timezone, etc and expects an array of entries to show.

Client side fc already provides tools for that. Here we should use the function version of the "entries" option. This could call the server side, fetch the data and handle the result.

**Comment by aetasoul** [comment]
I'll take a look at this this evening or tomorrow during the day.

**Comment by aetasoul** [comment]
Let me check the V4.0.3 for the other issue, after that i'll upgrate to v4.1.0

**Comment by aetasoul** [comment]
Hi @stefanuebe 
Compiling the parent leads to some test failure.

```
[INFO] Running org.vaadin.stefan.fullcalendar.FullCalendarTest
[ERROR] Tests run: 31, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.078 s <<< FAILURE! - in org.vaadin.stefan.fullcalendar.FullCalendarTest
[ERROR] testGetEntriesByClosedDateTimeInterval  Time elapsed: 0.015 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Searched for:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start of day to filter start + 1ns


but found:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start of day to filter start + 1ns
NM: Filter end to end of day
NM: Filter end to filter end
NM: Filter start to filter start
NM: Start of day to filter start


These have been found, but should not match:
NM: Filter end to end of day
NM: Filter end to filter end
NM: Filter start to filter start
NM: Start of day to filter start
 ==> expected: <6> but was: <10>
	at org.vaadin.stefan.fullcalendar.FullCalendarTest.testGetEntriesByClosedDateTimeInterval(FullCalendarTest.java:374)

[ERROR] testGetEntriesByClosedDateTimeIntervalWithoutFilterEnd  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Searched for:M: Filter end - 1ns to end of day
M: Filter end to end of day
M: Filter end to filter end
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start / end at end of day
M: Start of day to filter start + 1ns


but found:M: Filter end - 1ns to end of day
M: Filter end to end of day
M: Filter end to filter end
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start / end at end of day
M: Start of day to filter start + 1ns
NM: Filter start to filter start
NM: Start of day to filter start


These have been found, but should not match:
NM: Filter start to filter start
NM: Start of day to filter start
 ==> expected: <9> but was: <11>
	at org.vaadin.stefan.fullcalendar.FullCalendarTest.testGetEntriesByClosedDateTimeIntervalWithoutFilterEnd(FullCalendarTest.java:481)

[ERROR] testGetEntriesByDate  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Searched for:M: Filter end - 1ns to end of month
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Last year to filter start + 1ns


but found:M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Last year to filter start + 1ns
NM: Last year to filter start


Expected these to be found, but we did not:
M: Filter end - 1ns to end of month
M: Filter start + 1ns to filter end
M: Inside of filter timespan


These have been found, but should not match:
NM: Last year to filter start
 ==> expected: <6> but was: <4>
	at org.vaadin.stefan.fullcalendar.FullCalendarTest.testGetEntriesByDate(FullCalendarTest.java:592)

[ERROR] testGetEntriesByDateTimeIntervalWithoutFilterStart  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Searched for:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Filter start to filter start
M: Inside of filter timespan
M: Start / end at start of day
M: Start of day to filter start
M: Start of day to filter start + 1ns


but found:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Filter start to filter start
M: Inside of filter timespan
M: Start / end at start of day
M: Start of day to filter start
M: Start of day to filter start + 1ns
NM: Filter end to end of day
NM: Filter end to filter end


These have been found, but should not match:
NM: Filter end to end of day
NM: Filter end to filter end
 ==> expected: <9> but was: <11>
	at org.vaadin.stefan.fullcalendar.FullCalendarTest.testGetEntriesByDateTimeIntervalWithoutFilterStart(FullCalendarTest.java:427)

[INFO] Running org.vaadin.stefan.fullcalendar.JsonUtilsTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.vaadin.stefan.fullcalendar.JsonUtilsTest
[INFO] Running org.vaadin.stefan.fullcalendar.TimezoneTests
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.vaadin.stefan.fullcalendar.TimezoneTests
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   FullCalendarTest.testGetEntriesByClosedDateTimeInterval:374 Searched for:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start of day to filter start + 1ns


but found:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start of day to filter start + 1ns
NM: Filter end to end of day
NM: Filter end to filter end
NM: Filter start to filter start
NM: Start of day to filter start


These have been found, but should not match:
NM: Filter end to end of day
NM: Filter end to filter end
NM: Filter start to filter start
NM: Start of day to filter start
 ==> expected: <6> but was: <10>
[ERROR]   FullCalendarTest.testGetEntriesByClosedDateTimeIntervalWithoutFilterEnd:481 Searched for:M: Filter end - 1ns to end of day
M: Filter end to end of day
M: Filter end to filter end
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start / end at end of day
M: Start of day to filter start + 1ns


but found:M: Filter end - 1ns to end of day
M: Filter end to end of day
M: Filter end to filter end
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Start / end at end of day
M: Start of day to filter start + 1ns
NM: Filter start to filter start
NM: Start of day to filter start


These have been found, but should not match:
NM: Filter start to filter start
NM: Start of day to filter start
 ==> expected: <9> but was: <11>
[ERROR]   FullCalendarTest.testGetEntriesByDate:592 Searched for:M: Filter end - 1ns to end of month
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Inside of filter timespan
M: Last year to filter start + 1ns


but found:M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Last year to filter start + 1ns
NM: Last year to filter start


Expected these to be found, but we did not:
M: Filter end - 1ns to end of month
M: Filter start + 1ns to filter end
M: Inside of filter timespan


These have been found, but should not match:
NM: Last year to filter start
 ==> expected: <6> but was: <4>
[ERROR]   FullCalendarTest.testGetEntriesByDateTimeIntervalWithoutFilterStart:427 Searched for:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Filter start to filter start
M: Inside of filter timespan
M: Start / end at start of day
M: Start of day to filter start
M: Start of day to filter start + 1ns


but found:M: Filter end - 1ns to end of day
M: Filter start + 1ns to filter end
M: Filter start to filter end
M: Filter start to filter end - 1ns
M: Filter start to filter start
M: Inside of filter timespan
M: Start / end at start of day
M: Start of day to filter start
M: Start of day to filter start + 1ns
NM: Filter end to end of day
NM: Filter end to filter end


These have been found, but should not match:
NM: Filter end to end of day
NM: Filter end to filter end
 ==> expected: <9> but was: <11>
[INFO] 
[ERROR] Tests run: 78, Failures: 4, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for fullcalendar-parent 4.1.0-SNAPSHOT:
[INFO] 
[INFO] FullCalendar for Flow .............................. FAILURE [  3.108 s]
[INFO] FullCalendar Scheduler for Flow .................... SKIPPED
[INFO] Full Calendar web component demo ................... SKIPPED
[INFO] fullcalendar-parent ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.403 s
[INFO] Finished at: 2022-02-08T22:07:13+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project fullcalendar2: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Users\Virtuali\Desktop\Progetti\vaadin_fullcalendar\addon\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by aetasoul** [comment]
Can't test it in details with my project, the upgrade version is working (I need to analyze it in details)

I think you can release it without problems, I'll review my project Friday and fix any issue

**Comment by stefanuebe** [comment]
Integrated with release version 4.1.0.
