### ISSUE TITLE
Doesn't work with 23.3.0

### ISSUE THREAD

**Issue by simasch** [stefanuebe/vaadin_fullcalendar#159]
When using Fullcalendar with Vaadin 23.3.0 the application no longer starts. 
In the browser log I see

```
(anonymous) @ index.ts:32
vdom.js:3 Uncaught (in promise) Error: Please import the top-level fullcalendar lib before attempting to import a plugin.
    at vdom.js:3:11

```

**Comment by aetasoul** [comment]
Can you provide more details?

Java version
Code to reproduce the problem

**Comment by simasch** [comment]
@aetasoul Please find a reproducible example:

Make sure you checkout the branch fullcalendar-issue

https://github.com/simasch-scratches/datapicker-validation/tree/fullcalendar-issue

**Comment by aetasoul** [comment]
I'll check it

**Comment by stefanuebe** [comment]
Might be a problem regarding the time, when the plugins are registered. Not sure why this comes up with 23.3, but it seems to be a known issue. At least stackoverflow provides a lot of Q&A regarding this. Trying to reproduce and test those.

**Comment by stefanuebe** [comment]
https://github.com/primefaces/primevue/issues/1211

**Comment by stefanuebe** [comment]
Released with 4.1.4. Please countercheck, if it also works for you

**Comment by simasch** [comment]
@stefanuebe No doesn't work for me

Please find a reproducible example here: https://github.com/simasch-scratches/datapicker-validation/tree/fullcalendar-issue
Make sure you checkout the branch fullcalendar-issue

**Comment by stefanuebe** [comment]
Yes, you are right. On the first load I still get the issue, but on subsequent calls it does not occur anymore. That is really strange.

**Comment by stefanuebe** [comment]
Can you try if it works for you, when you change the imports in the full-calendar.js to

```
import '@fullcalendar/core/vdom'; 
import '@fullcalendar/core';
```

**Comment by simasch** [comment]
@stefanuebe Yes with this imports it works!

**Comment by stefanuebe** [comment]
Alright, then 4.1.5 is the version to go

**Comment by simasch** [comment]
Thanks for your very fast support!

**Comment by simasch** [comment]
Unfortunately in one application the calendar is not displayed.

```
FlowClient.js:197 Uncaught ReferenceError: Calendar is not defined
    at FullCalendarWithTooltip._initCalendar (full-calendar.js:137:34)
    at FullCalendarWithTooltip._initCalendar (full-calendar-with-tooltip.js:10:9)
    at FullCalendarWithTooltip.getCalendar (full-calendar.js:97:18)
    at FullCalendarWithTooltip.setOption (full-calendar.js:454:29)
    at Object.eval (eval at bu (FlowClient.js:1067:101), <anonymous>:3:11)
    at bu (FlowClient.js:1067:166)
    at au (FlowClient.js:1016:277)
    at $t (FlowClient.js:624:57)
    at Fr (FlowClient.js:527:18)
    at as.bs [as gb] (FlowClient.js:1076:20456)
    at LB (FlowClient.js:985:221)
    at Ir (FlowClient.js:1072:303)
    at Yr.Zr [as I] (FlowClient.js:1076:20222)
    at $k (FlowClient.js:454:29)
    at Ar (FlowClient.js:1074:1160)
    at Br (FlowClient.js:1055:401)
    at Ot.Qt [as Bb] (FlowClient.js:1076:23688)
    at oC.pC [as O] (FlowClient.js:1076:36950)
    at XMLHttpRequest.<anonymous> (FlowClient.js:633:63)
    at Ab (FlowClient.js:468:29)
    at Db (FlowClient.js:936:56)
    at XMLHttpRequest.<anonymous> (FlowClient.js:670:46)
```
