### ISSUE TITLE
FullCalendarWithTooltip initClandar fails with 4.1.5

### ISSUE THREAD

**Issue by simasch** [stefanuebe/vaadin_fullcalendar#160]
Unfortunately in one application the calendar is not displayed with version 4.1.5

FlowClient.js:197 Uncaught ReferenceError: Calendar is not defined
    at FullCalendarWithTooltip._initCalendar (full-calendar.js:137:34)
    at FullCalendarWithTooltip._initCalendar (full-calendar-with-tooltip.js:10:9)
    at FullCalendarWithTooltip.getCalendar (full-calendar.js:97:18)
    at FullCalendarWithTooltip.setOption (full-calendar.js:454:29)
    at Object.eval (eval at bu (FlowClient.js:1067:101), <anonymous>:3:11)
    at bu (FlowClient.js:1067:166)
    at au (FlowClient.js:1016:277)
    at $t (FlowClient.js:624:57)
    at Fr (FlowClient.js:527:18)
    at as.bs [as gb] (FlowClient.js:1076:20456)
    at LB (FlowClient.js:985:221)
    at Ir (FlowClient.js:1072:303)
    at Yr.Zr [as I] (FlowClient.js:1076:20222)
    at $k (FlowClient.js:454:29)
    at Ar (FlowClient.js:1074:1160)
    at Br (FlowClient.js:1055:401)
    at Ot.Qt [as Bb] (FlowClient.js:1076:23688)
    at oC.pC [as O] (FlowClient.js:1076:36950)
    at XMLHttpRequest.<anonymous> (FlowClient.js:633:63)
    at Ab (FlowClient.js:468:29)
    at Db (FlowClient.js:936:56)
    at XMLHttpRequest.<anonymous> (FlowClient.js:670:46)

**Comment by simasch** [comment]
Please find a reproducible example here: https://github.com/simasch-scratches/datapicker-validation/tree/fullcalendar-issue
Make sure you checkout the branch fullcalendar-issue

**Comment by stefanuebe** [comment]
Looks like I accidentally removed the {Calendar} import. Never do three things at a time in a place with poor internet and kids around you.

**Comment by simasch** [comment]
Looks good! Thank you!
