### ISSUE TITLE
Caused by: java.lang.ClassCastException: class [Z cannot be cast to class org.vaadin.stefan.fullcalendar.JsonItem$Key ([Z is in module java.base of loader 'bootstrap'; org.vaadin.stefan.fullcalendar.JsonItem$Key is in unnamed module of loader

### ISSUE THREAD

**Issue by simasch** [stefanuebe/vaadin_fullcalendar#161]
I tried to run the app with Jacoco Java agent and I get this exception:

```
java.lang.ExceptionInInitializerError: null
        at org.vaadin.stefan.fullcalendar.JsonItem$Key.readStaticField(JsonItem.java:1284) ~[fullcalendar2-4.1.6.jar:4.1.6]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
        at org.vaadin.stefan.fullcalendar.JsonItem$Key.readStaticKeyFields(JsonItem.java:1277) ~[fullcalendar2-4.1.6.jar:4.1.6]
        at org.vaadin.stefan.fullcalendar.JsonItem$Key.readAndRegisterKeys(JsonItem.java:1246) ~[fullcalendar2-4.1.6.jar:4.1.6]
        at org.vaadin.stefan.fullcalendar.JsonItem$Key.readAndRegisterKeysAsUnmodifiable(JsonItem.java:1232) ~[fullcalendar2-4.1.6.jar:4.1.6]
        at org.vaadin.stefan.fullcalendar.Entry.<clinit>(Entry.java:52) ~[fullcalendar2-4.1.6.jar:4.1.6]
        at ch.tosca.common.ui.component.ToscaCalendar.loadHolidays(ToscaCalendar.java:308) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaCalendar.<init>(ToscaCalendar.java:69) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaCalendarBuilder.build(ToscaCalendarBuilder.java:21) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaCalendarBuilder.build(ToscaCalendarBuilder.java:9) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilderUtil.lambda$addComponents$0(ToscaPanelBuilderUtil.java:56) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilderUtil.addComponents(ToscaPanelBuilderUtil.java:47) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanel.initialize(ToscaPanel.java:73) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaGroupPanel.<init>(ToscaGroupPanel.java:53) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaGroupPanelBuilder.build(ToscaGroupPanelBuilder.java:26) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaGroupPanelBuilder.build(ToscaGroupPanelBuilder.java:10) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilderUtil.lambda$addComponents$0(ToscaPanelBuilderUtil.java:56) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilderUtil.addComponents(ToscaPanelBuilderUtil.java:47) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanel.initialize(ToscaPanel.java:73) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanel.<init>(ToscaPanel.java:52) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilder.build(ToscaPanelBuilder.java:26) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilder.build(ToscaPanelBuilder.java:10) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanel.lambda$setVisible$0(ToscaSplitPanel.java:100) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at ch.tosca.common.ui.component.ToscaSplitPanel.setVisible(ToscaSplitPanel.java:95) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaBasePanelBuilder.configurePanel(ToscaBasePanelBuilder.java:14) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanelBuilder.build(ToscaSplitPanelBuilder.java:32) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanelBuilder.build(ToscaSplitPanelBuilder.java:14) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanel.lambda$setVisible$0(ToscaSplitPanel.java:100) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at ch.tosca.common.ui.component.ToscaSplitPanel.setVisible(ToscaSplitPanel.java:95) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaBasePanelBuilder.configurePanel(ToscaBasePanelBuilder.java:14) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanelBuilder.build(ToscaSplitPanelBuilder.java:32) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanelBuilder.build(ToscaSplitPanelBuilder.java:14) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanel.lambda$setVisible$0(ToscaSplitPanel.java:100) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at ch.tosca.common.ui.component.ToscaSplitPanel.setVisible(ToscaSplitPanel.java:95) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaBasePanelBuilder.configurePanel(ToscaBasePanelBuilder.java:14) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanelBuilder.build(ToscaSplitPanelBuilder.java:32) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaSplitPanelBuilder.build(ToscaSplitPanelBuilder.java:14) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilderUtil.lambda$addComponents$0(ToscaPanelBuilderUtil.java:56) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilderUtil.addComponents(ToscaPanelBuilderUtil.java:47) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanel.initialize(ToscaPanel.java:73) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanel.<init>(ToscaPanel.java:52) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilder.build(ToscaPanelBuilder.java:26) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.component.ToscaPanelBuilder.build(ToscaPanelBuilder.java:10) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.module.Module.createContent(Module.java:543) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.module.Module.init(Module.java:493) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.module.ToscaModule.init(ToscaModule.java:630) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.common.ui.module.ToscaModule.beforeEnter(ToscaModule.java:268) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:613) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:590) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:501) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:473) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:211) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.handleNavigation(JavaScriptBootstrapUI.java:317) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.navigate(JavaScriptBootstrapUI.java:225) ~[flow-server-23.3.0.jar:23.3.0]
        at ch.tosca.common.navigation.NavigationService.navigate(NavigationService.java:76) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.ui.login.LoginView.login(LoginView.java:202) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at ch.tosca.ui.login.LoginView.lambda$new$2db2d506$3(LoginView.java:110) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at com.vaadin.flow.component.KeyEventListener.onComponentEvent(KeyEventListener.java:67) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.KeyEventListener.onComponentEvent(KeyEventListener.java:30) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-23.3.0.jar:23.3.0]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:75) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419) ~[flow-server-23.3.0.jar:23.3.0]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1564) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369) ~[flow-server-23.3.0.jar:23.3.0]
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-23.3.0.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.69.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:353) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:696) ~[tomcat-embed-core-9.0.69.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.24.jar:5.3.24]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.69.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at ch.tosca.common.trace.TraceFilter.doFilter(TraceFilter.java:26) ~[tosca-standard-22.2.63-SNAPSHOT.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.6.jar:2.7.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.24.jar:5.3.24]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.24.jar:5.3.24]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.69.jar:9.0.69]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.ClassCastException: class [Z cannot be cast to class org.vaadin.stefan.fullcalendar.JsonItem$Key ([Z is in module java.base of loader 'bootstrap'; org.vaadin.stefan.fullcalendar.JsonItem$Key is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @591f989e)
        at org.vaadin.stefan.fullcalendar.JsonItem$Key.readStaticField(JsonItem.java:1282) ~[fullcalendar2-4.1.6.jar:4.1.6]
        ... 147 common frames omitted
```

Any idea what could be the problem?

**Comment by stefanuebe** [comment]
Nope, sorry. Never used JaCoCo in any way.

**Comment by simasch** [comment]
It seems that it's a problem with the Java Module System and the FieldUtils.readStaticField that uses Reflection.
Unfortunately, I couldn't find anything with Google.

**Comment by aetasoul** [comment]
Never used it. Can you share a reproducible example?

**Comment by simasch** [comment]
Repo: https://github.com/simasch-scratches/datapicker-validation
Branch: fullcalendar-issue

    mvn package -Pproduction

    java -javaagent:c:/apps/jacoco/lib/jacocoagent.jar -jar datepicker-validation-1.0-SNAPSHOT.jar

**Comment by simasch** [comment]
Jacoc can be downloaded here: https://www.eclemma.org/jacoco/

**Comment by stefanuebe** [comment]
Not sure, if it is related to our dynamic json item model, that backs the Entry class. With the next major version, I plan to roll that back to the previous approach of having simple POJOs, that will be converted to json items to be transported to the client (as the client in memory management will be removed and thus we do not need that anymore). 

Might be, that this solves this issue, too.

**Comment by simasch** [comment]
It must have something to to with Reflection. So if you go back to POJOs I assume that will solve the problem

**Comment by stefanuebe** [comment]
The branch v6 contains a first compilable and runnable draft of the next major. Except for resources, that seem not to work as expected, the demo should work. So I guess you could checkout the branch, if you want, and see, if Jacoco runs better now.

**Comment by stefanuebe** [comment]
Version 6 has been released.

**Comment by stefanuebe** [comment]
If it still is an issue simply reopen this one please.

**Comment by simasch** [comment]
Thank you! I'll test it.
