### ISSUE TITLE
Frontend Build failed

### ISSUE THREAD

**Issue by daemono** [stefanuebe/vaadin_fullcalendar#178]
Every time when i execute mvn spring-boot:run

i becom the error in console:

2023-11-09 14:12:49.973  INFO 28972 --- [onPool-worker-9] dev-webpack                              : Running webpack to compile frontend resources. This may take a moment, please stand by...
2023-11-09 14:13:00.823 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196mERROR in ../node_modules/@vaadin/flow-frontend/vaadin-full-calendar/full-calendar.ts[0m
2023-11-09 14:13:00.824 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196mModule build failed (from ../node_modules/ts-loader/index.js):[0m
2023-11-09 14:13:00.824 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196mError: TypeScript emitted no output for C:\git\kundm\KundMV2\KundMWebV2\node_modules\@vaadin\flow-frontend\vaadin-full-calendar\full-calendar.ts. By default, ts-loader will not compile .ts files in node_modules.[0m
2023-11-09 14:13:00.824 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196mYou should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.[0m
2023-11-09 14:13:00.824 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196mSee: https://github.com/Microsoft/TypeScript/issues/12358[0m
2023-11-09 14:13:00.824 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196m    at makeSourceMapAndFinish (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:53:18)[0m
2023-11-09 14:13:00.824 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196m    at successLoader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:40:5)[0m
2023-11-09 14:13:00.825 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196m    at Object.loader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:23:5)[0m
2023-11-09 14:13:00.825 ERROR 28972 --- [        webpack] dev-webpack                              : [38;5;196m @ ../target/frontend/generated-flow-imports.js 62:0-69[0m
2023-11-09 14:13:00.825  INFO 28972 --- [onPool-worker-9] dev-webpack                              : Started webpack-dev-server. Time: 10855ms

 have already set @EnableVadin to this package but still not possible to compile the frontend. Any suggestions?

**Comment by daemono** [comment]
@aetasoul still the same issue, here the log:
------------------ Starting Frontend compilation. ------------------
[0m2023-11-10 13:46:41.755  INFO 32196 --- [onPool-worker-9] dev-webpack                              : Running webpack to compile frontend resources. This may take a moment, please stand by...
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mERROR in ../node_modules/@vaadin/flow-frontend/License.ts[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mModule build failed (from ../node_modules/ts-loader/index.js):[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mError: TypeScript emitted no output for C:\git\kundm\KundMV2\KundMWebV2\node_modules\@vaadin\flow-frontend\License.ts. By default, ts-loader will not compile .ts files in node_modules.[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mYou should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mSee: https://github.com/Microsoft/TypeScript/issues/12358[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at makeSourceMapAndFinish (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:53:18)[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at successLoader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:40:5)[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at Object.loader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:23:5)[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m @ ../node_modules/@vaadin/flow-frontend/VaadinDevmodeGizmo.js 12:0-95 724:8-19 781:12-30 1124:12-26 1127:12-30 1130:12-29[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mERROR in ../node_modules/@vaadin/flow-frontend/vaadin-full-calendar/full-calendar-scheduler.ts[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mModule build failed (from ../node_modules/ts-loader/index.js):[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mError: TypeScript emitted no output for C:\git\kundm\KundMV2\KundMWebV2\node_modules\@vaadin\flow-frontend\vaadin-full-calendar\full-calendar-scheduler.ts. By default, ts-loader will not compile .ts files in node_modules.[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mYou should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mSee: https://github.com/Microsoft/TypeScript/issues/12358[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at makeSourceMapAndFinish (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:53:18)[0m
2023-11-10 13:46:51.843 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at successLoader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:40:5)[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at Object.loader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:23:5)[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m @ ../target/frontend/generated-flow-imports.js 61:0-79[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mERROR in ../node_modules/@vaadin/flow-frontend/vaadin-full-calendar/full-calendar.ts[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mModule build failed (from ../node_modules/ts-loader/index.js):[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mError: TypeScript emitted no output for C:\git\kundm\KundMV2\KundMWebV2\node_modules\@vaadin\flow-frontend\vaadin-full-calendar\full-calendar.ts. By default, ts-loader will not compile .ts files in node_modules.[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mYou should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196mSee: https://github.com/Microsoft/TypeScript/issues/12358[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at makeSourceMapAndFinish (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:53:18)[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at successLoader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:40:5)[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m    at Object.loader (C:\git\kundm\KundMV2\KundMWebV2\node_modules\ts-loader\dist\index.js:23:5)[0m
2023-11-10 13:46:51.844 ERROR 32196 --- [        webpack] dev-webpack                              : [38;5;196m @ ../target/frontend/generated-flow-imports.js 62:0-69[0m
2023-11-10 13:46:51.844  INFO 32196 --- [onPool-worker-9] dev-webpack                              : Started webpack-dev-server. Time: 10094ms

**Comment by aetasoul** [comment]
Vaadin version?

**Comment by daemono** [comment]
I have it resolved in meantime. Many thanks

**Comment by aetasoul** [comment]
Can you give some more information to the other people? Maybe it could help someone else in future
