### ISSUE TITLE
DateTimeParseException when adding DatesRenderedListener

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#24]
Hi.

First of all thanks a lot for your great work. I really appreciate it ;)

I try out this Vaadin 14 FC integration and got the following exception when adding a DatesRenderedListener.
```
... 
Caused by: java.time.format.DateTimeParseException: Text '2019-10-07T00:00:00Z' could not be parsed, unparsed text found at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952) ~[?:1.8.0_211]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[?:1.8.0_211]
	at java.time.LocalDate.parse(LocalDate.java:400) ~[?:1.8.0_211]
	at java.time.LocalDate.parse(LocalDate.java:385) ~[?:1.8.0_211]
	at org.vaadin.stefan.fullcalendar.DatesRenderedEvent.<init>(DatesRenderedEvent.java:49) ~[fullcalendar2-2.0.0.RC2.jar:2.0.0.RC2]
	at sun.reflect.GeneratedConstructorAccessor131.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211]
	at com.vaadin.flow.component.ComponentEventBus.createEventForDomEvent(ComponentEventBus.java:409) ~[flow-server-2.0.14.jar:2.0.14]
	... 59 more
```

I created the instance by:

```
private final FullCalendar fullCalendar = FullCalendarBuilder.create().build();
private LocalDate visibleStartDate;
private LocalDate visibleEndDate;
...
fullCalendar.addDatesRenderedListener( listener -> {
	visibleStartDate = listener.getStart();
	visibleEndDate = listener.getEnd();
} );
```

The Entry instances are created via
```
Entry basicEvent = new Entry( app.getUUID(), caption,
		app.getStartV8(),
		app.getEndV8(),
		app.isAllDay(),
		true,
		color,
		app.getDescription()
	);
```
where app.getStartV8() are LocalDateTime instances.

My bet is that the date parsing logic in DatesRenderedEvent should be aware of a LocalDateTime instance as well.

Thanks a lot for your great work ;)

**Comment by OriEy** [comment]
Probably has the same cause, but the same Error also accures in DayNumberClickedEvent.
I guess it happens for other Events as well.

**Comment by stefanuebe** [comment]
Yes, you're right, the issue source is, that I reintegrated the moment library and simply misinterpreted a function. Will fix that soon.

**Comment by stefanuebe** [comment]
See RC4
