### ISSUE TITLE
NPE when entering the calendar

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#29]
Hi Stefan.

I tried out the new RC5 and when I enter the Calendar I get immediately get the following exception:
```
Caused by: java.lang.NullPointerException
	at org.vaadin.stefan.fullcalendar.DatesRenderedEvent.getLocalDate(DatesRenderedEvent.java:99) ~[fullcalendar2-2.0.0.RC5.jar:2.0.0.RC5]
	at org.vaadin.stefan.fullcalendar.DatesRenderedEvent.<init>(DatesRenderedEvent.java:52) ~[fullcalendar2-2.0.0.RC5.jar:2.0.0.RC5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_211]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45009) ~[?:1.8.0_211]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45012) ~[?:1.8.0_211]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_211]
	at com.vaadin.flow.component.ComponentEventBus.createEventForDomEvent(ComponentEventBus.java:409) ~[flow-server-2.0.18.jar:2.0.18]
	... 60 more
```

When getLocalDate(...) is called eventData argument is null.

Thanks for your work ;)

**Comment by stefanuebe** [comment]
You're right. Problem seems to be, that I just prevent the creation of the event details, but not firing the event. itself (which will be fired with null data then). Will fix that.

**Comment by stefanuebe** [comment]
Are there any client side error messages (e.g. in the log)?

**Comment by stefanuebe** [comment]
It makes sense, that there is a NPE, since the current impl simply prevented the creation of the event details, not firing the event at all. I cannot reproduce it, but fixed it, that the event firing is also prevented, when no event details are generated. Will test it and upload RC6 then

**Comment by kamuffe** [comment]
Hi Stefan.

Thanks for the really quick fix. In RC6 it is working now.
The NPE does not occur anymore.

I tested again with RC5 but didn't see any client side errors.
