### ISSUE TITLE
DateTimeParseException with 2.3.1

### ISSUE THREAD

**Issue by kamuffe** [stefanuebe/vaadin_fullcalendar#58]
Hi Stefan.

I just tried the new FC integration 2.3.1 and git the following exception:
```
...
Caused by: java.time.format.DateTimeParseException: Text '2020-5-1' could not be parsed at index 5
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[?:1.8.0_211]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[?:1.8.0_211]
	at java.time.LocalDate.parse(LocalDate.java:400) ~[?:1.8.0_211]
	at java.time.LocalDate.parse(LocalDate.java:385) ~[?:1.8.0_211]
	at org.vaadin.stefan.fullcalendar.JsonUtils.parseDateTimeString(JsonUtils.java:172) ~[fullcalendar2-2.3.1.jar:2.3.1]
	at org.vaadin.stefan.fullcalendar.ViewRenderEvent.getLocalDate(ViewRenderEvent.java:85) ~[fullcalendar2-2.3.1.jar:2.3.1]
	at org.vaadin.stefan.fullcalendar.ViewRenderEvent.<init>(ViewRenderEvent.java:78) ~[fullcalendar2-2.3.1.jar:2.3.1]
	at org.vaadin.stefan.fullcalendar.DatesRenderedEvent.<init>(DatesRenderedEvent.java:47) ~[fullcalendar2-2.3.1.jar:2.3.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_211]
```

Best,
Kamuffe

**Comment by stefanuebe** [comment]
Ah, damn, might be related to the removal of moment.js. Needs to formatDate method in the client side to add leading 0s. I'll see if I can fix that nearby

**Comment by stefanuebe** [comment]
Looks like date handling is a bit buggy now due to removal of moment js. Will be reintroduced, that should also fix this issue here. (2.3.2 then)

**Comment by kamuffe** [comment]
Hi Stefan.

Wow, this was quite fast. Thanks a lot. The exception went away in 2.3.2 ;)

Best,
Kamuffe
